// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	CreateExperience(ctx context.Context, arg CreateExperienceParams) (Experience, error)
	CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteExperience(ctx context.Context, id int32) error
	DeleteProject(ctx context.Context, id int32) error
	GetAbout(ctx context.Context) (About, error)
	GetCurrentExperience(ctx context.Context) ([]Experience, error)
	GetFeaturedProjects(ctx context.Context) ([]Project, error)
	GetPastExperience(ctx context.Context) ([]Experience, error)
	GetProjectBySlug(ctx context.Context, slug string) (Project, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	ListExperience(ctx context.Context) ([]Experience, error)
	ListProjects(ctx context.Context) ([]Project, error)
	SearchProjects(ctx context.Context, dollar_1 sql.NullString) ([]Project, error)
	UpdateExperience(ctx context.Context, arg UpdateExperienceParams) (Experience, error)
	UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error)
	UpsertAbout(ctx context.Context, arg UpsertAboutParams) (About, error)
}

var _ Querier = (*Queries)(nil)
