name: Deploy to Firebase Hosting on merge

'on':
  push:
    branches:
      - main
jobs:
  setup_pnpm:
    runs-on: ubuntu-latest
    outputs:
      cache-key: ${{ steps.pnpm-cache.outputs.key }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup PNPM
        uses: pnpm/action-setup@v3
        with:
          version: 8

  build_and_deploy:
    needs: setup_pnpm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache PNPM modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ needs.setup_pnpm.outputs.cache-key }}
      - run: pnpm install --frozen-lockfile && pnpm build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_PORTFOLIO_30890 }}'
          channelId: live
          projectId: portfolio-30890