name: PNPM CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build

    steps:
      - name: git-checkout
        uses: actions/checkout@v3

      - name: pnpm-setup
        uses: pnpm/action-setup@v3
        with:
          version: 8
